=== gokmonk/maitreya7/src/xml/WesternChartConfigs.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT WesternChartConfigs (Config)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Config (FrameType|Chart2Planets|Chart2Zodiac5Degree|Chart2Zodiac1Degree|Chart2Zodiac|Houses|WidgetBackground|Pen|OuterZodiac|Zodiac|Zodiac1Degree|Zodiac5Degree|ZodiacSymbols|Planets|Aspects|InnerHouse|OuterHouse|Angles|PlanetMarkerLength|ZodiacalSigns|Brush)*>
<!ATTLIST Config
    Description CDATA #IMPLIED
    Extends CDATA #IMPLIED
    Name CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT OuterZodiac (Pen|Radius)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Radius (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Zodiac (Radius)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Zodiac1Degree (Radius)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Zodiac5Degree (Radius)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ZodiacSymbols (Pen|Radius)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Planets (Radius)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Aspects (FrameType|Brush|Radius)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT InnerHouse (FrameType|Pen|Radius)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT OuterHouse (Radius)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Angles (OuterCircle|InnerCircle)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT InnerCircle (Radius)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT OuterCircle (Radius)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT PlanetMarkerLength (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ZodiacalSigns (UseStockBrushList|GlobalTextColor|BrushSequence|SymbolZoomFactor|RotateSymbols|SymbolType)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT SymbolType (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT RotateSymbols (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT SymbolZoomFactor (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Brush (Inputfile|Style|Color)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Color (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Style (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Pen (LineWidth|Style|Linewidth|Color)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Linewidth (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT WidgetBackground (Brush)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Inputfile (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT BrushSequence (Brush)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT GlobalTextColor (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Houses (UseStockBrushList|GlobalTextColor|BrushSequence)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT LineWidth (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Chart2Zodiac (Radius)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Chart2Zodiac1Degree (Radius)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Chart2Zodiac5Degree (Radius)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Chart2Planets (Radius)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT UseStockBrushList (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT FrameType (#PCDATA)>

=== gokmonk/maitreya7/src/xml/WesternChartConfigs.xml
<?xml version="1.0"?>
<!DOCTYPE WesternChartConfigs SYSTEM "WesternChartConfigs.dtd">
<WesternChartConfigs>
    <Config Name="Default">
		</Config>

    <Config Name="Default/Colored">
        <Houses>
            <UseStockBrushList>True</UseStockBrushList>
        </Houses>
        <ZodiacalSigns>
            <UseStockBrushList>True</UseStockBrushList>
        </ZodiacalSigns>
		</Config>

    <Config Name="Big Signs">
        <OuterZodiac>
            <Radius>92</Radius>
        </OuterZodiac>
        <Zodiac>
            <Radius>69</Radius>
        </Zodiac>
        <Zodiac1Degree>
            <Radius>71</Radius>
        </Zodiac1Degree>
        <Zodiac5Degree>
            <Radius>73</Radius>
        </Zodiac5Degree>
        <ZodiacSymbols>
            <Radius>84</Radius>
        </ZodiacSymbols>
        <Planets>
            <Radius>62</Radius>
        </Planets>
        <Aspects>
            <Radius>40</Radius>
        </Aspects>
        <InnerHouse>
            <Radius>40</Radius>
        </InnerHouse>
        <OuterHouse>
            <Radius>69</Radius>
        </OuterHouse>

				<InnerTransitZodiac>
						<Radius>40</Radius>
				</InnerTransitZodiac>
				<InnerTransitZodiac1Degree>
						<Radius>42</Radius>
				</InnerTransitZodiac1Degree>
				<InnerTransitZodiac5Degree>
						<Radius>44</Radius>
				</InnerTransitZodiac5Degree>
				<InnerTransitPlanets>
						<Radius>48</Radius>
				</InnerTransitPlanets>

				<Angles>
            <InnerCircle>
                <Radius>40</Radius>
            </InnerCircle>
            <OuterCircle>
                <Radius>97</Radius>
            </OuterCircle>
        </Angles>
        <PlanetMarkerLength>2</PlanetMarkerLength>
        <ZodiacalSigns>
            <SymbolType>0</SymbolType>
            <RotateSymbols>True</RotateSymbols>
            <SymbolZoomFactor>250</SymbolZoomFactor>
        </ZodiacalSigns>
    </Config>

    <Config Name="Big Signs/Colored" Extends="Big Signs">
        <Houses>
            <UseStockBrushList>True</UseStockBrushList>
            <GlobalTextColor>Grey</GlobalTextColor>
        </Houses>
        <ZodiacalSigns>
            <UseStockBrushList>True</UseStockBrushList>
            <GlobalTextColor>White</GlobalTextColor>
        </ZodiacalSigns>
    </Config>

    <Config Name="Big Signs 2" Extends="Big Signs">
        <ZodiacalSigns>
            <SymbolType>1</SymbolType>
        </ZodiacalSigns>
    </Config>

    <Config Name="Big Signs 2/Colored" Extends="Big Signs 2">
        <ZodiacalSigns>
            <SymbolType>1</SymbolType>
        </ZodiacalSigns>
        <Houses>
            <UseStockBrushList>True</UseStockBrushList>
            <GlobalTextColor>Grey</GlobalTextColor>
        </Houses>
        <ZodiacalSigns>
            <UseStockBrushList>True</UseStockBrushList>
            <GlobalTextColor>White</GlobalTextColor>
        </ZodiacalSigns>
    </Config>

    <Config Name="Houses Outside">
        <Zodiac>
            <Radius>72</Radius>
        </Zodiac>
        <ZodiacSymbols>
            <Radius>76</Radius>
        </ZodiacSymbols>
        <Zodiac1Degree>
            <Radius>74</Radius>
        </Zodiac1Degree>
        <Zodiac5Degree>
            <Radius>76</Radius>
        </Zodiac5Degree>
        <OuterZodiac>
            <Radius>85</Radius>
        </OuterZodiac>
        <InnerHouse>
            <Radius>85</Radius>
        </InnerHouse>
        <ZodiacSymbols>
            <Radius>80</Radius>
        </ZodiacSymbols>
        <OuterHouse>
            <Radius>93</Radius>
        </OuterHouse>
        <Planets>
            <Radius>65</Radius>
        </Planets>
        <Aspects>
            <Radius>50</Radius>
        </Aspects>
        <Angles>
            <InnerCircle>
                <Radius>50</Radius>
            </InnerCircle>
            <OuterCircle>
                <Radius>97</Radius>
            </OuterCircle>
        </Angles>
    </Config>

    <Config Name="Houses Outside/Colored" Extends="Houses Outside">
        <Houses>
            <UseStockBrushList>True</UseStockBrushList>
            <GlobalTextColor>Grey</GlobalTextColor>
        </Houses>
        <ZodiacalSigns>
            <UseStockBrushList>True</UseStockBrushList>
            <GlobalTextColor>White</GlobalTextColor>
        </ZodiacalSigns>
    </Config>

    <Config Name="Astrolog">
        <Brush>
            <Color>black</Color>
            <Style>wxSOLID</Style>
        </Brush>
        <Pen>
            <Color>white</Color>
            <Linewidth>2</Linewidth>
            <Style>wxSOLID</Style>
        </Pen>
        <WidgetBackground>
            <Brush>
                <Color>black</Color>
                <Style>wxSOLID</Style>
            </Brush>
        </WidgetBackground>

        <ZodiacSymbols>
            <Radius>87</Radius>
        </ZodiacSymbols>
        <Zodiac1Degree>
            <Radius>81</Radius>
        </Zodiac1Degree>
        <Zodiac5Degree>
            <Radius>83</Radius>
        </Zodiac5Degree>
        <OuterZodiac>
            <Radius>92</Radius>
        </OuterZodiac>
        <Planets>
            <Radius>73</Radius>
        </Planets>
        <Aspects>
            <Radius>40</Radius>
        </Aspects>
        <InnerHouse>
            <Radius>40</Radius>
        </InnerHouse>
        <OuterHouse>
            <Radius>79</Radius>
        </OuterHouse>

        <Angles>
            <InnerCircle>
                <Radius>40</Radius>
            </InnerCircle>
            <OuterCircle>
                <Radius>97</Radius>
            </OuterCircle>
        </Angles>

				<InnerTransitZodiac>
						<Radius>40</Radius>
				</InnerTransitZodiac>
				<InnerTransitZodiac1Degree>
						<Radius>42</Radius>
				</InnerTransitZodiac1Degree>
				<InnerTransitZodiac5Degree>
						<Radius>44</Radius>
				</InnerTransitZodiac5Degree>

				<InnerTransitPlanets>
						<Radius>48</Radius>
				</InnerTransitPlanets>
        <PlanetMarkerLength>2</PlanetMarkerLength>
    </Config>

    <Config Name="Yellow">
        <WidgetBackground>
            <Brush>
                <Color>black</Color>
                <Style>wxSOLID</Style>
            </Brush>
        </WidgetBackground>
        <Pen>
            <Color>yellow</Color>
            <Linewidth>2</Linewidth>
            <Style>wxSOLID</Style>
        </Pen>
        <OuterZodiac>
            <Radius>92</Radius>
            <Pen>
                <Color>Yellow</Color>
                <Linewidth>5</Linewidth>
            </Pen>
        </OuterZodiac>
        <ZodiacSymbols>
            <Radius>87</Radius>
            <Pen>
                <Color>Yellow</Color>
                <Linewidth>5</Linewidth>
            </Pen>
        </ZodiacSymbols>
        <InnerHouse>
            <Radius>40</Radius>
            <Pen>
                <Color>Yellow</Color>
                <Linewidth>2</Linewidth>
            </Pen>
        </InnerHouse>
        <Aspects>
            <Radius>40</Radius>
        </Aspects>
        <Angles>
            <InnerCircle>
                <Radius>40</Radius>
            </InnerCircle>
            <OuterCircle>
                <Radius>97</Radius>
            </OuterCircle>
        </Angles>

				<InnerTransitZodiac>
						<Radius>40</Radius>
				</InnerTransitZodiac>
				<InnerTransitZodiac1Degree>
						<Radius>42</Radius>
				</InnerTransitZodiac1Degree>
				<InnerTransitZodiac5Degree>
						<Radius>44</Radius>
				</InnerTransitZodiac5Degree>
				<InnerTransitPlanets>
						<Radius>48</Radius>
				</InnerTransitPlanets>
    </Config>

    <Config Name="Madera/transparent" Description="A walnut-like theme">
        <WidgetBackground>
            <Brush>
                <Style>wxSTIPPLE</Style>
                <Inputfile>madera.jpg</Inputfile>
            </Brush>
        </WidgetBackground>
    </Config>

    <Config Name="Mardera/colored signs and houses">
        <WidgetBackground>
            <Brush>
                <Style>wxSTIPPLE</Style>
                <Inputfile>madera.jpg</Inputfile>
            </Brush>
        </WidgetBackground>
        <ZodiacalSigns>
            <BrushSequence>
							<Brush>
								<Inputfile>madera.jpg</Inputfile>
								<RotateHue>330</RotateHue>
							</Brush>
							<Brush>
								<Inputfile>madera.jpg</Inputfile>
								<RotateHue>15</RotateHue>
							</Brush>
							<Brush>
								<Inputfile>madera.jpg</Inputfile>
								<RotateHue>60</RotateHue>
							</Brush>
							<Brush>
								<Inputfile>madera.jpg</Inputfile>
								<RotateHue>150</RotateHue>
							</Brush>
            </BrushSequence>
            <GlobalTextColor>black</GlobalTextColor>
        </ZodiacalSigns>
        <Houses>
            <BrushSequence>
							<Brush>
								<Inputfile>madera.jpg</Inputfile>
								<RotateHue>330</RotateHue>
							</Brush>
							<Brush>
								<Inputfile>madera.jpg</Inputfile>
								<RotateHue>15</RotateHue>
							</Brush>
							<Brush>
								<Inputfile>madera.jpg</Inputfile>
								<RotateHue>60</RotateHue>
							</Brush>
							<Brush>
								<Inputfile>madera.jpg</Inputfile>
								<RotateHue>150</RotateHue>
							</Brush>
            </BrushSequence>
            <GlobalTextColor>black</GlobalTextColor>
        </Houses>
    </Config>

    <Config Name="Marble">
        <WidgetBackground>
            <Brush>
                <Style>wxSTIPPLE</Style>
                <Inputfile>marble.jpg</Inputfile>
            </Brush>
        </WidgetBackground>
    </Config>

  <Config Name="Marble/Colored signs" extends="Marble">
		<ZodiacalSigns>
			<BrushSequence>
				<Brush>
					<Inputfile>marble.jpg</Inputfile>
					<RotateHue>330</RotateHue>
				</Brush>
				<Brush>
					<Inputfile>marble.jpg</Inputfile>
					<RotateHue>15</RotateHue>
				</Brush>
				<Brush>
					<Inputfile>marble.jpg</Inputfile>
					<RotateHue>60</RotateHue>
				</Brush>
				<Brush>
					<Inputfile>marble.jpg</Inputfile>
					<RotateHue>150</RotateHue>
				</Brush>
			</BrushSequence>
		</ZodiacalSigns>
			<Houses>
					<BrushSequence>
