=== gokmonk/maitreya7/src/xml/yogas/YogaConfigs.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT YogaConfigs (Config)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Config (AllowHigherVargas|Rule|Group|Source|Effect|Description)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Description (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Effect (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Source (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Group (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Rule (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT AllowHigherVargas (#PCDATA)>

=== gokmonk/maitreya7/src/xml/yogas/41NakshtrasBrihatJataka.xml
<?xml version="1.0"?>
<!DOCTYPE YogaConfigs SYSTEM "YogaConfigs.dtd">
<YogaConfigs>
	<!--  1  -->
	<Config>
		<Description>Moon in Aswini</Description>
		<Effect>The person born In Aswini will be fond of decoration, handsome, popular, skilful and intelligent </Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Aswini;</Rule>
	</Config>

	<!--  2  -->
	<Config>
		<Description>Moon in Bharani</Description>
		<Effect>One born in Bharani will be determined, truthful, healthy, skilful and happy.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Bharani;</Rule>
	</Config>

	<!--  3  -->
	<Config>
		<Description>Moon in Krittika</Description>
		<Effect>The person born in Krittika will be a voracious enter, fond of otherâ€™s wives, attractive and renowned </Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Krittika;</Rule>
	</Config>

	<!--  4  -->
	<Config>
		<Description>Moon in Rohini</Description>
		<Effect>Rohini makes a man truthful, clean, following religious and moral principles, sweet in speech, fixed mind and handsome.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Rohini;</Rule>
	</Config>

	<!--  5  -->
	<Config>
		<Description>Moon in Mrigasira</Description>
		<Effect>Mrigasira-Capricious, skilful, cowardly, good speaker, hopeful, rich and enjoying.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Mrigasira;</Rule>
	</Config>

	<!--  6  -->
	<Config>
		<Description>Moon in Arudra</Description>
		<Effect>Aridra-Dissimulating in self-interest, proud, ungrateful, cruel and sinful.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Arudra;</Rule>
	</Config>

	<!--  7  -->
	<Config>
		<Description>Moon in Punarvasu</Description>
		<Effect>Punarvasu-Religious endurance, happy, good, dull, sickly, thirsty and pleased with small gifts.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Punarvasu;</Rule>
	</Config>

	<!--  8  -->
	<Config>
		<Description>Moon in Pushyami</Description>
		<Effect>Pushya-Control over passions, popular, learned, rich and charitable.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Pushyami;</Rule>
	</Config>

	<!--  9  -->
	<Config>
		<Description>Moon in Aslesha</Description>
		<Effect>Aslesha-Dissimulator, clever in selfishness, sinful, ungrateful and a cheat.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Aslesha;</Rule>
	</Config>

	<!--  10  -->
	<Config>
		<Description>Moon in Makha</Description>
		<Effect>Makha-Many servants and great wealth, enjoying, respector of elders and gods and very enterprising.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Makha;</Rule>
	</Config>

	<!--  11  -->
	<Config>
		<Description>Moon in Purva Phalgini</Description>
		<Effect>Pubba-Sweet speech, liberal, handsome, fond of traveling and royal servant.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == PurvaPhalgini;</Rule>
	</Config>

	<!--  12  -->
	<Config>
		<Description>Moon in Uttara Phalguni</Description>
		<Effect>Uttara-Popular, self-acquired property, enjoying and happy.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == UttaraPhalguni;</Rule>
	</Config>

	<!--  13  -->
	<Config>
		<Description>Moon in Hashta</Description>
		<Effect>Hasta-Enterprising, intelligent or (shameless), drunkard, cruel and thievish.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Hashta;</Rule>
	</Config>

	<!--  14  -->
	<Config>
		<Description>Moon in Chitta</Description>
		<Effect>Chitta-Using various clothes and garlands, good looks and limbs.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Chitta;</Rule>
	</Config>

	<!--  15  -->
	<Config>
		<Description>Moon in Swati</Description>
		<Effect>Swati-Polite, merchant, kind hearted, not able to endure thirst, sweet tongued and generous.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Swati;</Rule>
	</Config>

	<!--  16  -->
	<Config>
		<Description>Moon in Vishakha</Description>
		<Effect>Visakha-Jealous, avaricious, handsome, clever speaker and quarrelsome, or maker of money.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Vishakha;</Rule>
	</Config>

	<!--  17  -->
	<Config>
		<Description>Moon in Anuradha</Description>
		<Effect>Anuradha-Master or chief, living in foreign countries, not able to bear hunger and fond of traveling.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Anuradha;</Rule>
	</Config>

	<!--  18  -->
	<Config>
		<Description>Moon in Jeshta</Description>
		<Effect>Jyeshta-Few friends, contented, charitable, very irritable.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Jeshta;</Rule>
	</Config>

	<!--  19  -->
	<Config>
		<Description>Moon in Moola</Description>
		<Effect>Moola-Proud, rich happy, good, steady and enjoying.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Moola;</Rule>
	</Config>

	<!--  20  -->
	<Config>
		<Description>Moon in Purva Shadha</Description>
		<Effect>Purvashada-Good and pleasant wife, proud and a steady friend.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == PurvaShadha;</Rule>
	</Config>

	<!--  21  -->
	<Config>
		<Description>Moon in UttaraShadha</Description>
		<Effect>Uttarashada-Polite, knowing, virtuous, many friends, grateful and popular.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == UttaraShadha;</Rule>
	</Config>

	<!--  22  -->
	<Config>
		<Description>Moon in Sravana</Description>
		<Effect>Sravana-Rich surroundings, learned, good and liberal or liberal to wife, wealthy and renowned.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Sravana;</Rule>
	</Config>

	<!--  23  -->
	<Config>
		<Description>Moon in Dhanishta</Description>
		<Effect>Dhanishta-Liberal, rich, courageous, fond of music and money.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Dhanishta;</Rule>
	</Config>

	<!--  24  -->
	<Config>
		<Description>Moon in Satabishak</Description>
		<Effect>Satabhisha-Plain and truthful, striken from sorrow through females, etc., killer of enemies, adventurous and irreconcilable.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Satabishak;</Rule>
	</Config>

	<!--  25  -->
	<Config>
		<Description>Moon in Purva Bhadra</Description>
		<Effect>Poorvabhadra-Sorrowful, loss of money through females, skilful and miserly.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == PurvaBhadra;</Rule>
	</Config>

	<!--  26  -->
	<Config>
		<Description>Moon in Uttara Bhadra</Description>
		<Effect>Uttarabhadra-Good and witty speaker in society and meetings, happy, many children and grandchildren, successful over enemies and charitable.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == UttaraBhadra;</Rule>
	</Config>

	<!--  27  -->
	<Config>
		<Description>Moon in Revati</Description>
		<Effect>Revati-Well- developed organs, popular, courageous, clean and wealthy. developed organs, popular, courageous, clean and wealthy.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Revati;</Rule>
	</Config>

</YogaConfigs>
